---
title: "Extra Homework Set 2"
author: 
affiliation: "Dawson College Math 103"
abstract:
thanks:
keywords:
date:
output:
   html_document:
    highlight: default
    citation_package:
    keep_tex: false
    fig_caption: true
    latex_engine: pdflatex
fontsize: 11pt
geometry: margin=1in
bibliography:
biblio-style:
header-includes:
- \usepackage{indentfirst}
- \usepackage{graphicx}
- \usepackage{geometry}
- \usepackage{subfigure}
- \usepackage{amsmath}
- \usepackage{listings}
- \usepackage{tikz}
- \usetikzlibrary{matrix}
---

\vspace{0.25in}



# 1. 

Evaluate the following limits.  If the limit does not exist then explain why.

a. $\displaystyle \lim_{x\rightarrow -6} x^2+5x$

b. $\displaystyle \lim_{x\rightarrow 0} x^3 + 7x^2+15x+9$

c. $\displaystyle \lim_{x\rightarrow -2} 4^{x+4}$

d. $\displaystyle \lim_{x\rightarrow 7} x+2$

e. $\displaystyle \lim_{x\rightarrow -6} \frac{x-3}{x^3-3x^2-16x+48}$

f. $\displaystyle \lim_{x\rightarrow \frac{\pi}{2}} \cos(x^3+2x^2-23x-60)$

g. $\displaystyle \lim_{x\rightarrow 6} \frac{x^2-2x-3}{x-5}$

a. $\displaystyle \lim_{x\rightarrow 3} \frac{\sqrt{2x+3}-3}{x-3}$

**answers**: a. 6, b. 9, c. 16, d. 9, e. 1/20, f. 0.798, g. 21 h. 1/3
  

# 2.

Evaluate the following limits.

a. $\displaystyle \lim_{x\rightarrow 0} \frac{x-4}{4x-x^2}$

b. $\displaystyle \lim_{x\rightarrow -5} \frac{x^2-25}{x^2+2x-15}$

d. $\displaystyle \lim_{x\rightarrow 0} 2^{\displaystyle\frac{1}{x}}$

a. $\displaystyle \lim_{x\rightarrow 0} \frac{x}{3-\sqrt{x+9}}$

c. $\displaystyle \lim_{x \rightarrow -5^+} \frac{x^2-4}{x^3 +12x^2 + 47x+60}$

d. $\displaystyle \lim_{x \rightarrow 1} \frac{1}{x-1}$

e. $\displaystyle \lim_{x \rightarrow 0} \frac{x^2+3x}{x^3+5x^2+4x}$

**answers**: a. DNE, b. 5/4, c. DNE, d. 0, e. $\infty$, f. DNE, g. 3/4

# 3.

Evaluate the following limits.

a. $\displaystyle \lim_{x \rightarrow \infty} \frac{-x}{2x^2-5x+1}$

b. $\displaystyle \lim_{x \rightarrow -\infty} 4x^2-5x+4$

c. $\displaystyle \lim_{x \rightarrow \infty} \frac{2x^2-x+1}{5x^2-3}$

d. $\displaystyle \lim_{x \rightarrow \infty} \frac{5x^3 - 2x +1}{8x^2-1}$

e. $\displaystyle \lim_{x \rightarrow \infty} \frac{2x^3-x-3}{x-3}$

**answers**: a. 0, b. $\infty$, c. 2/5, d. $\infty$, e. $\infty$