---
title: "Extra Homework Set 4"
author: 
affiliation: "Dawson College Math 103"
abstract:
thanks:
keywords:
date:
output:
   html_document:
    highlight: default
    citation_package:
    keep_tex: false
    fig_caption: true
    latex_engine: pdflatex
fontsize: 11pt
geometry: margin=1in
bibliography:
biblio-style:
header-includes:
- \usepackage{indentfirst}
- \usepackage{graphicx}
- \usepackage{geometry}
- \usepackage{subfigure}
- \usepackage{amsmath}
- \usepackage{listings}
- \usepackage{tikz}
- \usetikzlibrary{matrix}
---

\vspace{0.25in}



# 1. 

Calculate the derivative of

a. $f(x) = 2x^4-3x^3+3x^2-8x+9$

b. $f(x) = \frac{1}{x^2}$

c. $g(x) = \displaystyle 7x^3-4x+\frac{1}{x}-\frac{1}{x^2}$


**answers**: a. $f'(x) = 8x^3-9x^2+6x^2-8$, b. $f'(x) =\displaystyle -\frac{2}{x^3}$, c. $g'(x) =\displaystyle 21x^2-x-\frac{1}{x^2}+\frac{2}{x^3}$ 
  
# 2.

Find the equation of the tangent line to the function at the given value of x.

a. $f(x) = 2x^4-3x^3+3x^2-8x+9$ at $x=1

b. $f(x) = \displaystyle \frac{1}{x^3}$ at $x=2$

c. $g(x) = \displaystyle x^2 - \frac{1}{x^2}$ at $x=-1$

**answer**: a. $y = 5x-8$ b. $y=\displaystyle - \frac{3}{16}x + \frac{1}{2}$ c. $y=-\displaystyle\frac{9}{4}x-\frac{9}{4}$ 

# 3.

Let

$$
f(x) = \begin{cases} x^2 & \text{if}\; x\leq 1 \\ ax+b & \text{if}\; x> 1 \end{cases}.
$$
Find the values of $a$ and $b$ such that $f(x)$ is continuous and differentiable at $x=1$.

**answers**: $a=2$ and $b=-1$

# 4.

Find the derivative of the following functions

a. $f(x) = (2x+1)(4x-3)$

b. $g(x) = (x-\displaystyle\frac{1}{x})(x^3-1)$

c. $f(x) = \displaystyle\frac{2x-1}{4x-3}$

c. $g(x) =\displaystyle\frac{\sqrt{x}+1}{x^2+1}$

d. $h(x) = \displaystyle\frac{x}{x^2-4}-\frac{x-1}{x^2+4}$

**answers**: a. $f'(x) = 16x-2$, b. $g'(x) = 4x^3-2x-1-\displaystyle\frac{1}{x^2}$, c. $\displaystyle\frac{-2}{(4x-3)^2}$, d. $\displaystyle\frac{-4x^{3/2}(\sqrt{x}+1)+x^2+1}{2\sqrt{x}(x^2+1)^2}$ e. $\displaystyle\frac{-2x^5-24x^4+16x^3-32x-128}{x^8-32x^4+256}$