---
title: "Extra Homework Set 1"
author: 
affiliation: "Dawson College Math 103"
abstract:
thanks:
keywords:
date:
output:
   html_document:
    highlight: default
    citation_package:
    keep_tex: false
    fig_caption: true
    latex_engine: pdflatex
fontsize: 11pt
geometry: margin=1in
bibliography:
biblio-style:
header-includes:
- \usepackage{indentfirst}
- \usepackage{graphicx}
- \usepackage{geometry}
- \usepackage{subfigure}
- \usepackage{amsmath}
- \usepackage{listings}
- \usepackage{tikz}
- \usetikzlibrary{matrix}
---

\vspace{0.25in}



# 1. 

Evaluate the expressions

a. $(7^{1/2})^4$

b. $\displaystyle\left(\frac{9^2\cdot9^{-1}}{9^{-4}}\right)^2$

b. $\displaystyle\sqrt{\frac{1}{2^6}}$

d. $\displaystyle 8^{-4/3}$

e. $\displaystyle \frac{16^{5/8}\cdot16^{1/2}}{16^{7/8}}$
  
**answers**: a. 49, b. $9^{10}$, c. 1/8, d. 1/16, e. 1/4


# 2.

Simplify each expression and write with only positive exponents.

a. $\displaystyle\left(\frac{x^3}{-27y^{-6}}\right)^{-2/3}$
a. $\displaystyle(x^2y^{-3})(x^{-5}y^3)$
b. $\displaystyle\left(\frac{(r^n)^4}{r^{5-2n}} \right)$
c. $\displaystyle \sqrt[\leftroot{-2}\uproot{2}6]{64x^8y^3}$
d. $\displaystyle \sqrt[\leftroot{-2}\uproot{2}3]{27r^6}\cdot\sqrt[\leftroot{-2}\uproot{2}3]{s^2t^4}$

**answers**: a. $\displaystyle\frac{-9}{x^2y^4}$, b. $\displaystyle\frac{1}{x^3}$, c. $r^{6n-5}$, d. $2x^{4/3}y^{1/2}$, e. $3r^2s^{3/2}t^{4/3}$

# 3.

Find the real roots of each equation by factoring

a. $x^2+x-12=0$
c. $3x^2-x-4=0$

d. $4t^2+2t-2=0$

b. $x^2 -1=0$

**answers**: a. -4, 3  b. -1, 4/3 c. -1, 1/2 d. $\pm 1$



# 4.

Evaluate

a. $4 + |-4|$

b. $|-12+4|+1$  

b. $\displaystyle \frac{|4-8|}{|16-12|}>4$

c. $|\sqrt{2}-1|+|3-\sqrt{2}|$

d. $|\pi -6|-3$

**answers**: a. 8 b. 9 c. false d. 2 e. -0.14159


# 5.

a. Find the equation of the line passing through the points $(-1,-3)$ and $(3,2)$
b. Find the equation of the line passing through the points $(-2,5)$ and $(1,-4)$
c. Find the y intercept of the line passing through the points $(-2,5)$ and $(1,-4)$
d. Find the equation of the line perpendicular to the previous problem passing through the point $(-2,5)$
e. Determine if the lines $AB$ and $CD$ are parallel if $A(2,3),B(2,-2)$ and $C(-2,4),D(-2,5)$.

**answers**: a. $y=\frac{5}{4}x-\frac{7}{4}$, b. $y = -3x-10$, c. -1 d. $y = x/3+17/5$, e. parallel